### ISSUE TITLE
GRNet excution

### ISSUE THREAD

**Issue by Maverick172** [mattia93/GRNet#1]
The file does not contain the file path for "source_dir". How should this issue be handled?
![Uploading source_dir.png…]()

**Comment by Maverick172** [comment]
![Uploading source_dir.png…]()

**Comment by mattia93** [comment]
Hi!
`source_dir` is a temporary folder where the unzipped files are stored. Without changing the source code you can name it 'files_temp_dir`. I also notice it was initialized twice, so I fixed that. Let me know if it works for you

**Comment by Maverick172** [comment]
Thank you for your answer. Do I need to fully extract the test sets for each domain when running the code with the data in the testsets/TS_PerGen/ directory?
